export const state = () => ({
    products:[{
        vehicleID:50,
        brandName:"Toyota",
        vehicleIdentificationNumber:"XDR12",
        price:120000,
        color:"Jet Black",
        description:"Bhut badiya",
        location:"Delhi",
        kmDriven:400,
        images:["https://www.mercedes-amg.com/dam/hq/models/Modeloverview/bodytype/mercedes-amg-modeloverview-c-class-coupe-cla45s-C118-118354-ID103558-1440x810.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg.image_file.820.461.1611236664825.file/cq5dam.web.1280.1280.jpg"
                , "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"Maruti Swift ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"Rahul",
           dealerContactNo:7844562103,
           dealerAddress:"2/8 Plotno.555",
        },
         extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
      {
        vehicleID:51,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/n/cw/ec/47336/e-class-exterior-right-front-three-quarter-26.jpeg?q=85"
        , "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
    
      {
        vehicleID:52,
        brandName:"Mercedies",
        vehicleIdentificationNumber:"XDR22",
        price:170000000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/n/cw/ec/47336/e-class-exterior-right-front-three-quarter.jpeg?q=85",
         "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
     
      {
        vehicleID:53,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/cw/ec/30146/MercedesBenz-CClass-Exterior-136697.jpg?wm=0&q=85",
         "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
    
      {
        vehicleID:54,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/n/cw/ec/43718/glc-exterior-right-front-three-quarter-3.jpeg?q=85",
        "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
    
      {
        vehicleID:55,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/cw/ec/30149/MercedesBenz-SClass-Exterior-122263.jpg?wm=0&q=85",
        "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
    
      {
        vehicleID:56,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/n/cw/ec/20865/amg-gt-exterior-right-front-three-quarter-60800.jpeg?q=85",
        "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
    
      {
        vehicleID:57,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://imgd.aeplcdn.com/664x374/ec/A0/b2/19601/img/m/Mercedes-Benz-S-Coupe-Right-Front-Three-Quarter-54969_ol.jpg?v=201711021421&q=85",
        "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
      {
        vehicleID:58,
        brandName:"Mahindra",
        vehicleIdentificationNumber:"XDR22",
        price:1700000,
        color:"white",
        description:"Nice Look ",
        location:"Bangaluru",
        kmDriven:400,
        images:["https://static.autox.com/uploads/cars/2021/03/mercedesbenz-a-class-limousine.jpg",
        "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
        modelName:"XUV500 W7 ",
        fuelType:"Diesel",
        dealerInfo:{
           dealerName:"shivam",
           dealerContactNo:7844562108,
           dealerAddress:"2/8 Plotno.555",
        },
        extraInfo:{
           auxCompatibility:true,
           accidental:false,
           floodAffected:false,
           insuranceType:"Third Party",
           registrationPlace:"”KL”",
           powerSteering:true,
           color:"”White”",
           insurance:true,
           condition:"”Used”",
           numberOfOwners:"”First”",
           variant:"”CelerioVXi”",
           exchange:true,
           typeofCar:"”Hatchback”",
           radio:true,
           USBCompatibility:true,
           transmission:"”Manual”",
           airConditioning:true
        },
        Features:{
           discount:30,
           getFinance:true,
           makeAnOffer:true,
           premium:true,
           favourite:true
        }
      },
      {
         vehicleID:60,
         zipcode:"10030",
         brandName:"Limosine",
         vehicleIdentificationNumber:"XDR22",
         price:1700000,
         color:"white",
         description:"Nice Look ",
         rating:5,
         location:"Bangaluru",
         kmDriven:400,
         images:["https://images-na.ssl-images-amazon.com/images/I/619HD3H8LwL._AC_SL1000_.jpg",
         "https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-saloon/facts-and-lines/equipment-packages/interior-light/_jcr_content/par/productinfotextimage/media2/slides/videoimageslide_2e16/image.MQ6.12.20180426150119.jpeg","https://i.ytimg.com/vi/ymh-OFPJ-ZQ/maxresdefault.jpg","https://www.mercedes-benz.co.id/passengercars/mercedes-benz-cars/models/e-class/e-class-coupe/facts-and-lines/designo/designo-theme/_jcr_content/par/xcitingscenedefiniti_1557540234/image.MQ6.8.20180823135502.jpeg"],
         modelName:"XUV500 W7 ",
         fuelType:"Diesel",
         dealerInfo:{
            dealerName:"shivam",
            dealerContactNo:7844562108,
            dealerAddress:"2/8 Plotno.555",
         },
         extraInfo:{
            auxCompatibility:true,
            accidental:false,
            floodAffected:false,
            insuranceType:"Third Party",
            registrationPlace:"”KL”",
            powerSteering:true,
            color:"”White”",
            insurance:true,
            condition:"”Used”",
            numberOfOwners:"”First”",
            variant:"”CelerioVXi”",
            exchange:true,
            typeofCar:"”Hatchback”",
            radio:true,
            USBCompatibility:true,
            transmission:"”Manual”",
            airConditioning:true
         },
         Features:{
            discount:30,
            getFinance:true,
            makeAnOffer:true,
            premium:false,
            favourite:true
         }
       },
    ]
})
export const mutations = {
    addItem(state, id){
        let item = state.products.find(product => product.id == id)
        state.myRentals.push(item)
    },
}

export const getters = {
    getProductById: (state) => (id) => {
        return state.products.find(product => product.vehicleID == id)
    } 
}